# Makefile for MenuGen
#
# Copyright 2010, Stephen Fryatt
#
# This file really needs to be run by GNUMake.

.PHONY:	all

BUILD_DATE := $(shell date "+%-d %b %Y")

ifeq ($(TARGET),riscos)
  CC := $(wildcard $(GCCSDK_INSTALL_CROSSBIN)/*gcc)

  # Compilation flags

  CCFLAGS := -mlibscl -mhard-float -static -mthrowback -Wall -O2 -fno-strict-aliasing -mpoke-function-name
else
  CC := gcc

  # Compilation flags

  CCFLAGS := -Wall -O2 -fno-strict-aliasing -DBUILD_DATE="\"$(BUILD_DATE)\""
endif

# Set up source and object files.

INCLUDES := -I$(GCCSDK_INSTALL_ENV)/include

LINKS := -L$(GCCSDK_INSTALL_ENV)/lib

OBJS := data.o menugen.o parse.o stack.o

# Start to define the targets.

all:	menugen

menugen: $(OBJS)
	$(CC) $(CCFLAGS) $(LINKS) -o menugen $(OBJS)

# These targets should really be autogenerated.

menugen.o: menugen.c stack.h
	$(CC) $(CCFLAGS) $(INCLUDES) -o menugen.o -c menugen.c

data.o: data.c data.h
	$(CC) $(CCFLAGS) $(INCLUDES) -o data.o -c data.c

parse.o: parse.c parse.h
	$(CC) $(CCFLAGS) $(INCLUDES) -o parse.o -c parse.c

stack.o: stack.c stack.h
	$(CC) $(CCFLAGS) $(INCLUDES) -o stack.o -c stack.c
