# Makefile for MenuGen
#
# Copyright 2010, Stephen Fryatt
#
# This file really needs to be run by GNUMake.

ifeq ($(TARGET),riscos)
  CC := $(wildcard $(GCCSDK_INSTALL_CROSSBIN)/*gcc)

  # Compilation flags

  CCFLAGS := -mlibscl -mhard-float -static -mthrowback -Wall -O2 -fno-strict-aliasing -mpoke-function-name
else
  CC := gcc

  # Compilation flags

  CCFLAGS := -Wall -O2 -fno-strict-aliasing
endif

# Set up source and object files.

INCLUDES := -I$(GCCSDK_INSTALL_ENV)/include

LINKS := -L$(GCCSDK_INSTALL_ENV)/lib

OBJS := menugen.o stack.o

# Start to define the targets.

.PHONY:	all
all:	menugen

menugen: $(OBJS)
	$(CC) $(CCFLAGS) $(LINKS) -o menugen $(OBJS)

# These targets should really be autogenerated.

menugen.o: menugen.c stack.h
	$(CC) $(CCFLAGS) $(INCLUDES) -o menugen.o -c menugen.c

stack.o: stack.c stack.h
	$(CC) $(CCFLAGS) $(INCLUDES) -o stack.o -c stack.c
